target-version = "py310"
line-length = 110

[lint]
select = ["E", "F", "I", "W", "UP", "B", "SIM", "RUF"]
ignore = ["E501"]

[lint.per-file-ignores]
"**/tests/*" = ["B011"]
"prototype/*" = ["E", "F", "W", "UP", "B", "SIM", "RUF"]
"services/api/app/services/rasters.py" = ["SIM117"]
