from __future__ import annotations

import pandas as pd
import pytest


@pytest.fixture
def sample_school_df() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "School Name": "School A",
                "Province": "Province One",
                "District": "District One",
                "Locality": "Remote",
                "Latitude": -9.0,
                "Longitude": 147.0,
                "Number of Available Teachers": 10,
                "Total Number of Classrooms": 8,
                "Number of Permanent Classrooms": 6,
                "Number of Semi-Permanent Classrooms": 1,
                "Number of Bush Material Classrooms": 1,
                "Number of Houses for Teachers": 4,
                "Number of Libraries": 1,
                "Number of Workshops": 0,
                "Number of Practical Skills Buildings": 0,
                "Number of Home Economics Buildings": 0,
                "Number of Computer Labs": 1,
                "Number of Specialized Classrooms": 1,
                "Power Source": "Generator",
                "Water Source": "River",
                "Toilets": "Basic",
                "pop_with_access_walking": 1000,
                "pop_with_access_driving": 1200,
                "pop_with_access_cycling": 1100,
                "Access Walking (%)": 30,
                "Access Driving (%)": 45,
                "Access Cycling (%)": 35,
                "Fixed Broadband Download Speed (MB/s)": 5,
                "Mobile Internet Download Speed (MB/s)": 7,
                "Total Nighttime Luminosity": 500,
                "Secondary students per 1000 people": 60,
                "Rate of Grade 7 who progressed to Grade 10 (%)": 50,
                "Female students grade 7-12": 200,
                "Total enrollment Grade 7-12": 500,
                "Conflict Events": 3,
                "Conflict Fatalities": 0,
                "Conflict Population Exposure": 20,
                "R": 0.2,
                "lc_landterr_score": 0.3,
                "cachment_area_walking": "POLYGON ((147 -9, 147.001 -9, 147.001 -9.001, 147 -9.001, 147 -9))",
                "cachment_area_cycling": "POLYGON ((147 -9, 147.002 -9, 147.002 -9.002, 147 -9.002, 147 -9))",
                "cachment_area_driving": "POLYGON ((147 -9, 147.003 -9, 147.003 -9.003, 147 -9.003, 147 -9))",
            },
            {
                "School Name": "School B",
                "Province": "Province One",
                "District": "District One",
                "Locality": "Accessible",
                "Latitude": -9.1,
                "Longitude": 147.1,
                "Number of Available Teachers": 20,
                "Total Number of Classrooms": 10,
                "Number of Permanent Classrooms": 9,
                "Number of Semi-Permanent Classrooms": 1,
                "Number of Bush Material Classrooms": 0,
                "Number of Houses for Teachers": 6,
                "Number of Libraries": 2,
                "Number of Workshops": 1,
                "Number of Practical Skills Buildings": 1,
                "Number of Home Economics Buildings": 1,
                "Number of Computer Labs": 1,
                "Number of Specialized Classrooms": 1,
                "Power Source": "Grid",
                "Water Source": "Piped",
                "Toilets": "Upgraded",
                "pop_with_access_walking": 2000,
                "pop_with_access_driving": 2100,
                "pop_with_access_cycling": 2050,
                "Access Walking (%)": 60,
                "Access Driving (%)": 70,
                "Access Cycling (%)": 65,
                "Fixed Broadband Download Speed (MB/s)": 20,
                "Mobile Internet Download Speed (MB/s)": 15,
                "Total Nighttime Luminosity": 900,
                "Secondary students per 1000 people": 90,
                "Rate of Grade 7 who progressed to Grade 10 (%)": 80,
                "Female students grade 7-12": 350,
                "Total enrollment Grade 7-12": 700,
                "Conflict Events": 1,
                "Conflict Fatalities": 0,
                "Conflict Population Exposure": 10,
                "R": 0.1,
                "lc_landterr_score": 0.2,
                "cachment_area_walking": "POLYGON ((147.1 -9.1, 147.101 -9.1, 147.101 -9.101, 147.1 -9.101, 147.1 -9.1))",
                "cachment_area_cycling": "POLYGON ((147.1 -9.1, 147.102 -9.1, 147.102 -9.102, 147.1 -9.102, 147.1 -9.1))",
                "cachment_area_driving": "POLYGON ((147.1 -9.1, 147.103 -9.1, 147.103 -9.103, 147.1 -9.103, 147.1 -9.1))",
            },
            {
                "School Name": "School C",
                "Province": "Province Two",
                "District": "District Two",
                "Locality": "Very Remote",
                "Latitude": -8.0,
                "Longitude": 145.0,
                "Number of Available Teachers": None,
                "Total Number of Classrooms": 5,
                "Number of Permanent Classrooms": 2,
                "Number of Semi-Permanent Classrooms": 1,
                "Number of Bush Material Classrooms": 2,
                "Number of Houses for Teachers": None,
                "Number of Libraries": 0,
                "Number of Workshops": 0,
                "Number of Practical Skills Buildings": 0,
                "Number of Home Economics Buildings": 0,
                "Number of Computer Labs": 0,
                "Number of Specialized Classrooms": 0,
                "Power Source": None,
                "Water Source": None,
                "Toilets": None,
                "pop_with_access_walking": 500,
                "pop_with_access_driving": 700,
                "pop_with_access_cycling": 600,
                "Access Walking (%)": 20,
                "Access Driving (%)": 30,
                "Access Cycling (%)": 25,
                "Fixed Broadband Download Speed (MB/s)": 3,
                "Mobile Internet Download Speed (MB/s)": 4,
                "Total Nighttime Luminosity": 300,
                "Secondary students per 1000 people": 40,
                "Rate of Grade 7 who progressed to Grade 10 (%)": 35,
                "Female students grade 7-12": 80,
                "Total enrollment Grade 7-12": 250,
                "Conflict Events": 5,
                "Conflict Fatalities": 2,
                "Conflict Population Exposure": 40,
                "R": None,
                "lc_landterr_score": None,
                "cachment_area_walking": None,
                "cachment_area_cycling": None,
                "cachment_area_driving": None,
            },
        ]
    )

